name: product_2
description: A simple Dart-based eCommerce product management system.
version: 0.0.1
environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  test: ^1.16.0 # For unit testing

dev_dependencies:

